//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoAPI.Models.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarefaUsuario
    {
        public int ID { get; set; }
        public int TarefaID { get; set; }
        public int UsuarioID { get; set; }
        public string NivelPermissao { get; set; }
    
        public virtual Tarefa Tarefa { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
