//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoAPI.Models.Banco
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarefa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tarefa()
        {
            this.TarefaHist = new HashSet<TarefaHist>();
            this.TarefaUsuario = new HashSet<TarefaUsuario>();
        }
    
        public int ID { get; set; }
        public int ListaTarefaID { get; set; }
        public string Titulo { get; set; }
        public string Descricao { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public Nullable<System.DateTime> DataLimite { get; set; }
        public int Prioridade { get; set; }
        public string Status { get; set; }
        public byte[] Anexo { get; set; }
        public int CriadorID { get; set; }
        public bool Finalizada { get; set; }
    
        public virtual ListaTarefa ListaTarefa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaHist> TarefaHist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarefaUsuario> TarefaUsuario { get; set; }
    }
}
